# railway.toml - Configuration for deploying on Railway.app

[build]
# Specifies the command to run to build the application.
# This command installs all the Python packages listed in requirements.txt.
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
# Specifies the command to run to start the application after it's built.
# This command executes your main bot script.
startCommand = "python3 app.py"

# Specifies the restart policy for the application.
# "on-failure" means Railway will automatically restart the bot if it crashes.
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
